### ISSUE TITLE
OAuth 2.0 giving authentication error.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [mcohen01/node-quickbooks#154]
Hi!
I am using npm package node-quickbooks for using my quickbooks apis in my project. This is my file code in which I'm initializing the object and my function that fetchs the terms from quickbooks.
-----------------------------------------getTerms.js------------------------------------------------------------------------
const QuickBooks = require('node-quickbooks');
const qbo = new QuickBooks(
'my consumer key',
'my consumer secret',
'my oauth2 authorization code from playground',
false,
'my realmID',
false,
true,
null,
'2.0',
'my refresh token here from playground'
);

module.exports = {
    getTerms: criteria => {
        return new helper.promise((resolve, reject) => {
            qbo.findTerms(criteria, (err, terms) => {
                if (err) {
                    return reject(err);
                }
                return resolve(terms.QueryResponse.Term);
            });
        });
    }
}

===================================================

When I try to send api call by using the function it gives me error.

"fault": {
  "error": [{
    "message": "message=AuthorizationFailed; errorCode=003100; statusCode=403",
    "detail": null,
    "code": "3100",
    "element": null
   }],
  "type": "SERVICE"
}

I don't know what's wrong here. Can you please let me know what I'm doing wrong here or why it's giving error?

**Comment by dsandi** [comment]
Having the exact same issue, sandbox requests work fine.

**Comment by dsandi** [comment]
I managed to reproduce this issue and fix it. 

The reason you get a 3100 is because you are using the wrong tokens or the wrong environment.

If you generate an access token for production and you query the sandbox environment you will get this error.

If you generate an access token for sandbox and query the production environment you will get this error.

In my case I had an error in the Quickbooks constructor, so I was passing `"false"` instead of `false` to the is_sandbox flag so it was interpreted as true and it was hitting the sandbox environment with production access tokens.
