### ISSUE TITLE
Cannot query with undefined criteria

### ISSUE THREAD

**Issue by stephen-vetbadger** [mcohen01/node-quickbooks#167]
JSON.parse(JSON.stringify(undefined)) ---> great sadness

**Comment by mcohen01** [comment]
Fixed by https://github.com/mcohen01/node-quickbooks/pull/168. Thank you.

What can I say? I have no use for this project anymore so it gets no love. When folks submit [PRs](https://github.com/mcohen01/node-quickbooks/pull/166) I just don't look too closely at them most of the time. Sorry you ran into this.
